#!/bin/bash

# awesome-setup.sh
clear
echo "==================================================================="
echo "                   ⚠️  SYSTEM CONFIGURATION WARNING ⚠️"
echo "==================================================================="
echo ""
echo "🚨 IMPORTANT: This script will perform CRITICAL system modifications!"
echo "   Please read ALL of the following information carefully:"
echo ""
echo "🔴 PREREQUISITES & WARNINGS:"
echo ""
echo "📶  STABLE INTERNET CONNECTION REQUIRED"
echo "    • A reliable internet connection is essential throughout the process"
echo "    • Interruption may cause installation failures"
echo ""
echo "⏰  TIME REQUIREMENT: 10 MINUTES TO 1 HOUR"
echo "    • Process involves compiling packages and system configuration"
echo "    • Duration depends on your system speed and internet connection"
echo ""
echo "⚙️  SYSTEM CHANGES WILL BE MADE:"
echo "    • Default editor settings will be modified"
echo "    • New fonts will be installed"
echo "    • Syntax highlighting will be added"
echo "    • Default themes will be changed"
echo "    • Various system configurations will be adjusted"
echo ""
echo "🔑 PASSWORD REQUIRED MULTIPLE TIMES"
echo "    • You will be prompted for your sudo password SEVERAL times"
echo "    • This is normal for system-level installations"
echo "    • Have your password ready!"
echo ""
echo "-------------------------------------------------------------------"
echo ""
echo "🎯 TO PROCEED WITH AWESOME WM INSTALLATION:"
echo ""
echo "   Run this command in the terminal:"
echo "   ---------------------------------"
echo "   🔥 sudo bash awesome-install 🔥"
echo "   ---------------------------------"
echo ""
echo "❗ This terminal will remain open for you to execute the command."
echo "❗ Press any key to close this terminal when finished..."
echo ""
echo "==================================================================="
read -n 1 -s
