#!/bin/bash

# Nyelv érzékelése a rendszer nyelvi beállítása alapján
detect_language() {
    if [[ $LANG == *"hu"* ]] || [[ $LANGUAGE == *"hu"* ]]; then
        echo "hu"
    else
        echo "en"
    fi
}

# Részletes magyarázat a telepítési folyamatról
show_detailed_explanation() {
    local lang=$(detect_language)

    if [ "$lang" = "hu" ]; then
        echo ""
        echo "📋 RÉSZLETES TELEPÍTÉSI FOLYAMAT:"
        echo "=========================================="
        echo ""
        echo "1. 🗂️  SNAPPER BEÁLLÍTÁS (BTRFS SNAPSHOTOK)"
        echo "   • Automatikus rendszerpillanatképek beállítása"
        echo "   • Térkorlát: 0.5% (fél százalék)"
        echo "   • Heti/havi/éves snapshot takarítás"
        echo "   • Teszt snapshot készítése"
        echo ""
        echo "2. 🛠️  BTRFS KARBANTARTÁS IDŐZÍTŐK"
        echo "   • Heti BTRFS scrub (adatintegritás ellenőrzés)"
        echo "   • Havi BTRFS balance (adatkiegyenlítés)"
        echo "   • Heti TRIM (szabad terület optimalizálás)"
        echo "   • Garuda Linux-stílusú karbantartás"
        echo ""
        echo "3. 📦 CSOMAGOK TELEPÍTÉSE (100+ CSOMAG)"
        echo "   • Alap rendszereszközök: dmenu, rofi, flameshot, picom"
        echo "   • Fejlesztőeszközök: geany, git, fzf, bat, eza"
        echo "   • Hang/mediakezelés: mpd, mpc, playerctl, alsa-utils"
        echo "   • Hálózat: network-manager-applet, wavemon"
        echo "   • AUR csomagok: awesome-git, nordic témák, grayjay-bin"
        echo ""
        echo "4. 🎨 NORDIC TÉMA TELJES KÖRŰ BEÁLLÍTÁSA"
        echo "   • GTK téma: Nordic-standard-buttons"
        echo "   • Ikon téma: Nordzy-dark"
        echo "   • Kurzor téma: Nordic-cursors"
        echo "   • Betűtípus: FiraCode Nerd Font"
        echo "   • Kvantum témák rendszerszintű telepítése"
        echo "   • Rofi témák (Adi1090x stílus)"
        echo "   • LightDM beállítás nordic háttérrel"
        echo ""
        echo "5. ⚙️  RENDSZERBEÁLLÍTÁSOK"
        echo "   • Nano alapértelmezett szerkesztővé tétele"
        echo "   • Nano szintaxis kiemelés engedélyezése"
        echo "   • Fish shell beállítása (root számára)"
        echo "   • Automatikus lock (videólejátszás közben nem aktiválódik)"
        echo "   • XFCE beállítások optimalizálása"
        echo "   • Minden felhasználó számára konfigurálás (/etc/skel)"
        echo ""
        echo "6. 🎪 AWESOMEWM KONFIGURÁCIÓ"
        echo "   • AwesomeWM Copycats konfiguráció telepítése"
        echo "   • Automatikus symlinkek létrehozása"
        echo "   • Nordikus háttérképek telepítése"
        echo "   • Mission Impossibru szkriptek aktiválása"
        echo ""
        echo "7. 🧹 TAKARÍTÁS ÉS ÖNMEGSEMMISÍTÉS"
        echo "   • Régi telepítési fájlok eltávolítása"
        echo "   • Átmeneti fájlok törlése"
        echo "   • Telepítő szkript önmegsemmisítése"
        echo ""
        echo "⏰ BECSÜLT IDŐ: 15-60 perc (processzor és internet sebességtől függ)"
        echo ""
    else
        echo ""
        echo "📋 DETAILED INSTALLATION PROCESS:"
        echo "=========================================="
        echo ""
        echo "1. 🗂️  SNAPPER SETUP (BTRFS SNAPSHOTS)"
        echo "   • Automatic system snapshot configuration"
        echo "   • Space limit: 0.5% (half percent)"
        echo "   • Weekly/monthly/yearly snapshot cleanup"
        echo "   • Test snapshot creation"
        echo ""
        echo "2. 🛠️  BTRFS MAINTENANCE TIMERS"
        echo "   • Weekly BTRFS scrub (data integrity check)"
        echo "   • Monthly BTRFS balance (data rebalancing)"
        echo "   • Weekly TRIM (free space optimization)"
        echo "   • Garuda Linux-style maintenance"
        echo ""
        echo "3. 📦 PACKAGE INSTALLATION (100+ PACKAGES)"
        echo "   • System tools: dmenu, rofi, flameshot, picom"
        echo "   • Developer tools: geany, git, fzf, bat, eza"
        echo "   • Audio/media: mpd, mpc, playerctl, alsa-utils"
        echo "   • Network: network-manager-applet, wavemon"
        echo "   • AUR packages: awesome-git, nordic themes, grayjay-bin"
        echo ""
        echo "4. 🎨 COMPLETE NORDIC THEME SETUP"
        echo "   • GTK theme: Nordic-standard-buttons"
        echo "   • Icon theme: Nordzy-dark"
        echo "   • Cursor theme: Nordic-cursors"
        echo "   • Font: FiraCode Nerd Font"
        echo "   • System-wide Kvantum themes"
        echo "   • Rofi themes (Adi1090x style)"
        echo "   • LightDM setup with nordic background"
        echo ""
        echo "5. ⚙️  SYSTEM CONFIGURATIONS"
        echo "   • Set Nano as default editor"
        echo "   • Enable Nano syntax highlighting"
        echo "   • Configure Fish shell (for root)"
        echo "   • Automatic lock (disabled during video playback)"
        echo "   • Optimize XFCE settings"
        echo "   • Configure for all users (/etc/skel)"
        echo ""
        echo "6. 🎪 AWESOMEWM CONFIGURATION"
        echo "   • Install AwesomeWM Copycats configuration"
        echo "   • Create automatic symlinks"
        echo "   • Install Nordic wallpapers"
        echo "   • Activate Mission Impossibru scripts"
        echo ""
        echo "7. 🧹 CLEANUP AND SELF-DESTRUCT"
        echo "   • Remove old installation files"
        echo "   • Clean temporary files"
        echo "   • Self-destruct installer script"
        echo ""
        echo "⏰ ESTIMATED TIME: 15-60 minutes (depends on CPU and internet speed)"
        echo ""
    fi
}

# Fő üzenet megjelenítése
show_message() {
    local lang=$(detect_language)

    if [ "$lang" = "hu" ]; then
        echo "==================================================================="
        echo "                   ⚠️  RENDSZERBEÁLLÍTÁSI FIGYELMEZTETÉS ⚠️"
        echo "==================================================================="
        echo ""
        echo "🚨 FONTOS: Ez a szkript kritikus rendszermódosításokat hajt végre!"
        echo "   Kérjük, olvassa el figyelmesen az alábbi információkat:"
        echo ""
        echo "🔴 ELŐFELTÉTELEK & FIGYELMEZTETÉSEK:"
        echo ""
        echo "📶  STABIL INTERNETKAPCSOLAT SZÜKSÉGES"
        echo "    • Megbízható internetkapcsolat szükséges a folyamat során"
        echo "    • Megszakítás telepítési hibákat okozhat"
        echo "    • Több száz MB adatletöltés várható"
        echo ""
        echo "⏰  BECSLT IDŐIGÉNY: 15 PERCTŐL 60 PERCIG"
        echo "    • A folyamat csomagok fordítását és rendszerbeállításokat tartalmaz"
        echo "    • Az időtartam a rendszer sebességétől és internetkapcsolattól függ"
        echo "    • A folyamat több szakaszban fut, részletes leírást lásd alább"
        echo ""
        echo "⚙️  RENDSZERVERMÓDOSÍTÁSOK TÖRTÉNNEK:"
        echo "    • Snapper (BTRFS snapshot) konfiguráció készül"
        echo "    • BTRFS karbantartó időzítők aktiválódnak"
        echo "    • Több 100 csomag települ (GTK, QT, AwesomeWM, stb.)"
        echo "    • Nordic téma kerül telepítésre mindenhol"
        echo "    • Az alapértelmezett szerkesztő beállításai módosulnak"
        echo "    • Új betűtípusok települnek"
        echo "    • Szintaxis kiemelés kerül hozzáadásra"
        echo "    • Alapértelmezett témák változnak"
        echo "    • Különböző rendszerbeállítások módosulnak"
        echo "    • LightDM beállítások változnak"
        echo "    • Fish shell lesz az alapértelmezett (root számára)"
        echo ""
        echo "🔑 JELSZÓ TÖBBSZÖRI MEGADÁSA SZÜKSÉGES"
        echo "    • Többször is felkérjük a sudo jelszava megadására"
        echo "    • Ez normális a rendszerszintű telepítések során"
        echo "    • Legyen kéznél a jelszava!"
        echo ""

        # Részletes folyamat megjelenítése
        show_detailed_explanation

        echo "-------------------------------------------------------------------"
        echo ""
        echo "🎯 AZ AWESOME WM TELEPÍTÉSÉHEZ:"
        echo ""
        echo "   Futtassa a következő parancsot a terminálban:"
        echo "   ---------------------------------------------"
        echo "   🔥 sudo bash awesome-install 🔥"
        echo "   ---------------------------------------------"
        echo ""
        echo ""
        echo "❗ Ez a terminál nyitva marad a parancs végrehajtásához."
        echo "❗ Nyomjon meg egy billentyűt a terminál bezárásához, ha kész..."
        echo ""
        echo "==================================================================="
    else
        echo "==================================================================="
        echo "                   ⚠️  SYSTEM CONFIGURATION WARNING ⚠️"
        echo "==================================================================="
        echo ""
        echo "🚨 IMPORTANT: This script will perform CRITICAL system modifications!"
        echo "   Please read ALL of the following information carefully:"
        echo ""
        echo "🔴 PREREQUISITES & WARNINGS:"
        echo ""
        echo "📶  STABLE INTERNET CONNECTION REQUIRED"
        echo "    • A reliable internet connection is essential throughout the process"
        echo "    • Interruption may cause installation failures"
        echo "    • Several hundred MB of data will be downloaded"
        echo ""
        echo "⏰  TIME REQUIREMENT: 15 MINUTES TO 60 MINUTES"
        echo "    • Process involves compiling packages and system configuration"
        echo "    • Duration depends on your system speed and internet connection"
        echo "    • Process runs in multiple phases, see detailed description below"
        echo ""
        echo "⚙️  SYSTEM CHANGES WILL BE MADE:"
        echo "    • Snapper (BTRFS snapshot) configuration will be set up"
        echo "    • BTRFS maintenance timers will be activated"
        echo "    • Hundreds of packages will be installed (GTK, QT, AwesomeWM, etc.)"
        echo "    • Nordic theme will be installed system-wide"
        echo "    • Default editor settings will be modified"
        echo "    • New fonts will be installed"
        echo "    • Syntax highlighting will be added"
        echo "    • Default themes will be changed"
        echo "    • Various system configurations will be adjusted"
        echo "    • LightDM settings will be changed"
        echo "    • Fish shell will be set as default (for root)"
        echo ""
        echo "🔑 PASSWORD REQUIRED MULTIPLE TIMES"
        echo "    • You will be prompted for your sudo password SEVERAL times"
        echo "    • This is normal for system-level installations"
        echo "    • Have your password ready!"
        echo ""

        # Detailed process in English
        show_detailed_explanation

        echo "-------------------------------------------------------------------"
        echo ""
        echo "🎯 TO PROCEED WITH AWESOME WM INSTALLATION:"
        echo ""
        echo "   Run this command in the terminal:"
        echo "   ---------------------------------"
        echo "   🔥 sudo bash awesome-install 🔥"
        echo "   ---------------------------------"
        echo ""
        echo ""
        echo "❗ This terminal will remain open for you to execute the command."
        echo "❗ Press any key to close this terminal when finished..."
        echo ""
        echo "==================================================================="
    fi
}

# Fő program
show_message
read -n 1 -s
